
image:https://badges.gitter.im/sn127/tackler.svg["Gitter", link="https://gitter.im/sn127/tackler"]
image:https://travis-ci.org/sn127/tackler.svg?branch=stable["Build Status", link="https://travis-ci.org/sn127/tackler"]
image:https://coveralls.io/repos/github/sn127/tackler/badge.svg?branch=stable["Build Status", link="https://coveralls.io/github/sn127/tackler?branch=stable"]
image:https://maven-badges.herokuapp.com/maven-central/fi.sn127/tackler-core_2.12/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/fi.sn127/tackler-core_2.12"]
image:http://javadoc.io/badge/fi.sn127/tackler-core_2.12.svg?color=blue["javadoc", link="http://javadoc.io/page/fi.sn127/tackler-core_2.12/latest/fi/sn127/tackler/index.html"]
image:https://www.scala-js.org/assets/badges/scalajs-0.6.17.svg["Scala.js",link="https://www.scala-js.org"]

= Tackler

Tackler Ain't Calculator and Kernel for link:http://ledger-cli.org/[Ledger] Equivalent Records.
Why not?  - Because it uses simplified Ledger syntax.

So in other words, Tackler is accounting engine and reporting tool for link:http://plaintextaccounting.org/[text
based double-entry accounting].


== Features
* Tackler is link:docs/performance.adoc[fast]
* Support for link:docs/commodities.adoc[Commodities] and link:docs/currencies.adoc[Currencies]
* Text and link:docs/json.adoc[JSON] output formats for reports
** link:docs/server-api.adoc[Server API] for embedding Tackler core
** link:docs/client-api.adoc[Client API] for JVM and JS environments
* Integrated support with GIT version control system
** Can use plain filesystem or link:docs/git-storage.adoc[GIT repository] as data storage
** Natively supports splitting journal data to multiple files (shards)
* Clean and simple link:docs/journal.adoc[journal format]
* Strict account name validation with link:./docs/accounts.conf[Chart of Accounts]
* Multiple report and export types:
** link:docs/report-balance.adoc[Balance], link:docs/report-balance-group.adoc[Balance Groups] and link:docs/report-register.adoc[Register] Reports
** link:docs/export-equity.adoc[Equity] and link:docs/export-identity.adoc[Identity] Exports
* Support for link:./docs/txn-filters.adoc[Transaction Filters]
* Supports UTF-8 characters in transaction data (link:tests/parser/ok/par-02.ref.identity.txn[descriptions], link:tests/parser/ok/par-02.ref.reg.txt[comments], link:tests/parser/ok/id-chars-01.ref.identity.txn[account names])
* Supports ISO 8601 timestamps with link:tests/core/ok/time-dst-01.ref.identity.txn[timezones]
  and link:tests/core/ok/time-nano-01.ref.identity.txn[nanosecond] resolution
* Has good performance with link:docs/performance.adoc[large transaction set]
** Tackler is link:perf/results/hw00/[routinely tested] up to one million (1E6) transactions
** Tackler can process link:perf/results/readme.adoc[56000 txn/s] on Quad Core system
** With large transaction set, Tackler is faster than link:docs/perf-others.adoc[ledger-cli or other similar tools]
* Near 100% test coverage, link:tests/tests.yaml[all features are extensively tested]
* Extensive documentation: link:docs/readme.adoc[Index of Docs]


== Why Tackler?

Tackler's idea is provide *concise*, *minimal* and *reliable*
engine to process text-based human readable accounting records.

_Concise_ means that Tackler's journal format is semantically concise
and easy for humans to *reason about*.

_Minimal_ means that Tackler provides *minimum* set of features which are
needed for its operation.

_Reliable_ means that Tackler's behaviour is well known, tested
and it is *documented*.

All that said, Tackler can be used easily from command line
with normal personal accounting data sets.


=== Tackler Goals

* Minimal feature set, very simple and well defined input format
** *Tackler input journal is supposed to be produced by software and to be audited by human.*
    However, it must be possible to edit the journal by hand.

* Well known and defined behaviour

* Extensive user and developer documentation

* Error free, reliable and resilient
** Near perfect code and permutation test coverage

* Good performance
** Must be able to process hundreds of thousands of records with reasonable processing time and memory footprint
** Must have linear processing time characteristics
** Assumption: All transactions can be held in memory

* Provides backend and core components for text based accounting processing

* JVM and Multi platform support: Linux and Arm-Linux, it should be possible to run it on Windows

* GIT is used for data distribution and storage

Implementation language of Tackler is link:http://scala-lang.org/[Scala] 
and journal parsing is done with link:http://www.antlr.org/[ANTLR4].


== Documentation

User documentation is located under docs:

* link:./docs/readme.adoc[Index of all documentation]
* link:./docs/journal.adoc[Tackler journal format]
* link:./docs/usage.adoc[Usage of Tackler]
* link:./docs/configuration.adoc[Overview of Tackler Configuration]
* link:./docs/tackler.conf[Example of Tackler configuration]
* link:./docs/accounts.conf[Example of Tackler Chart of Accounts]
* link:./docs/trimix-filling-station.adoc[Example of Trimix Filling Station Accounting system (for scuba diving)]
* link:./docs/server-api.adoc[Server API]
* link:./docs/client-api.adoc[Client API]
* link:./docs/devel/readme.adoc[Developer's documentation]


== Todo, TEPs and Roadmap

At the moment, current set of active todo items is kept link:./todo[todo files].

There are Tackler Enhancement Proposals for planning and tracking implementation
of major new features. These are listed on link:docs/tep/readme.adoc[TEP index].

=== Roadmap

Extremely loosely defined roadmap is following:

* Reporting Server as separate project 
* Transaction filtering 
* Extending support for Units
* Profit and Loss (PnL) tracking
** Automatic conversions between different base units
** Support for unit handling with commodities  
* Extending support for Currencies and Commodities
** Price database

== Releases

For release information and version history details,
see link:./CHANGELOG.adoc[CHANGELOG].

Tackler-core is supposed to be usable as separate component.
Tackler-api is released for JVM and JS environments, and it is intended
to be used on the client side. See link:./docs/server-api.adoc[Server API]
and link:./docs/client-api.adoc[Client API] for additional information.

Dependency settings for SBT are:

    libraryDependencies += "fi.sn127" %%  "tackler-core" % "version-number"
    libraryDependencies += "fi.sn127" %%% "tackler-api"  % "version-number"

These are released on Maven Central Repository.

Tackler is under development, so if you enjoy calm seas
then it might be better to look
link:http://plaintextaccounting.org/[something else].

However, complex backward non-compatible changes to 
link:./docs/journal.adoc[Journal file format]
should be rare. At the moment Tackler is used in production for
operational data set.

Configuration files, command line interface and Client API (data models)
are more likely to subject of change.


== Contributing to Tackler

Contributions to the project are most welcome. See
link:./CONTRIBUTING.adoc[CONTRIBUTING] how you could help.

Your pull requests can be merged only if you can certify 
the link:./DCO[Developer Certificate of Origin (DCO), Version 1.1].
To certify DCO (e.g. sign-off your commit), you must add 
a `Signed-off-by` line to **every**  git commit message 
(e.g. by using `git commit -s`):

    Signed-off-by: github-account <your.real@email.address>

If you set your `user.name` and `user.email` in git config,
then git will include that line for you with `git commit -s`. 
These settings can be done per repository basis, 
so they don't have be global settings in your system. 
 
Please make sure that you sign-off all your PR's commits.


== Credits

See link:./THANKS.adoc[THANKS] for full list of credits.


== License

....
Copyright 2016-2018 SN127.fi Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
....

