= Performance results

These are ballpark results.
They are mostly used to validate sanity of used algorithms and overall performance.

Typically there are five runs, and slowest and fastest are dropped off from results.
Then Average is calculated based on remaining three.

Results with versions correspond to different ANTLR versions, and
most current version is without version string.


Results for Filesystem based storage:

 * link:./hw01/perf-1E3.txt[FS 1e3]
 * link:./hw01/perf-1E6.txt[FS 1e6]

Results for Git based storage (currently single thread based implementation):

 * link:./hw01/perf-git-1e3.txt[Git 1e3]
 * link:./hw01/perf-git-1e6.txt[Git 1e6]


== ANTRL versions

=== ANTLR 4.7

link:https://github.com/antlr/antlr4/releases/tag/4.7[Major changes of ANTLR 4.7]
include full 21-bit unicode support and deprecated `ANTLRFileStream et.al.`
These changes had no visible impact on Tackler's performance:

 * link:./hw01/perf-1E3-antlr-4.7.txt[]
 * link:./hw01/perf-1E6-antlr-4.7.txt[]

=== ANTLR 4.6

Initially used version

 * link:./hw01/perf-1E3-antlr-4.6.txt[]
 * link:./hw01/perf-1E6-antlr-4.6.txt[]
