= Performance test results

Tackler is performance tested to validate sanity of used algorithms and overall performance of system.

These are ballpark figures and  should be treated as such. Test method contains serious inaccuracies
especially with smaller tests set (load time of JVM, JIT, etc.), however it should be good enough to validate
selected algorithms and overall memory usage with increasing work load.

Performance test tools and scripts are located under link:../bin[bin] directory.

== Quad core system

This is low-end server system with quad core cpu. CPU has four cores and eight threads. All txn data can be cached
in memory. Full hardware info is link:./hw00/hw-info.txt[located here] and full test logs are link:./hw00/[here].

 * 1E3 txns:  2 sec, 250MB
 * 1E4 txns:  3 sec, 500MB
 * 1E5 txns:  5 sec, 1.4GB
 * 1E6 txns: 18 sec, 2.8GB, 56000 txn/s

CPU utilization is around 540%


== Dual core system

This system is normal-ish laptop system with dual core cpu. CPU has two cores and four threads. All txn data be cached
in memory. Full hardware info is link:./hw01/hw-info.txt[located here] and full test logs are link:./hw01/[here].

 * 1E3 txns:  3 sec, 200MB
 * 1E4 txns:  4 sec, 450MB
 * 1E5 txns:  8 sec, 1.4GB
 * 1E6 txns: 32 sec, 2.8GB, 31000 txn/s

CPU utilization is around 322%


== Test results

Used test data is 1E3, 1E4, 1E5 or 1E6 set of transactions. Tests are run for all
report types and for all formats.

There are five runs for each report and format types.


=== Results for Filesystem backend

 * link:./hw00/[HW00 (server) results]
 * link:./hw01/[HW01 (laptop) results]


=== Results for Git storage

These are based on currently single thread implementation:

 * link:./hw01/perf-git-1e3.txt[Git 1E3]
 * link:./hw01/perf-git-1e6.txt[Git 1E6]

