= Performance test results

Tackler is performance tested to validate sanity of used algorithms and overall performance of system.

These are ballpark figures and  should be treated as such. Test method contains serious inaccuracies
especially with smaller tests set (load time of JVM, JIT, etc.), however it should be good enough to validate
selected algorithms and overall memory usage with increasing work load.

Performance test data is generated by by link:../tools/generator[generator] tool.
Tools to run perf tests are located in link:./bin[bin].


== Test results

Used test sets are sets of 1E3, 1E4, 1E5 or 1E6 transactions. Tests are run for all
report types and for all formats. If version supports filtering then all above if also run
when filtering is enabled.

There are five runs for each report and format types.


== HW00: Quad core system

This is low-end server system with quad core cpu. CPU has four cores and eight threads.
All txn data can be cached in memory.

Balance report, CPU utilization is around 540%

 * 1E3 txns:  2 sec, 255MB
 * 1E4 txns:  3 sec, 500MB
 * 1E5 txns:  5 sec, 2.3GB
 * 1E6 txns: 18 sec, 4.2GB, 56000 txn/s

Link to link:./perf-hw00.adoc[detailed HW00 test results].

== HW01: Dual core system

This system is normal-ish laptop system with dual core cpu. CPU has two cores and four threads.
All txn data be cached in memory.

Balance report, CPU utilization is around 322%

 * 1E3 txns:  3 sec, 220MB
 * 1E4 txns:  4 sec, 470MB
 * 1E5 txns:  8 sec, 2.3GB
 * 1E6 txns: 32 sec, 4.3GB, 31000 txn/s

Link to link:./perf-hw01.adoc[detailed HW01 test results].

=== Git storage performance testing

Git backend is currently based on single thread implementation.

 * link:./hw01/perf-git-1e3.txt[Git 1E3]
 * link:./hw01/perf-git-1e6.txt[Git 1E6]
