= Performance results

These are ballpark results. They are mostly used to validate sanity of used 
algorithms and overall performance.

Typical performance of balance report on hyper-threaded Quad Core system is:

 * 1E3 txns:  2 sec, 250MB
 * 1E4 txns:  3 sec, 500MB
 * 1E5 txns:  5 sec, 1.4GB
 * 1E6 txns: 20 sec, 2.8GB 

CPU utilization is around 500%

== Actual test results

Used test data is 1E3, 1E4, 1E5 or 1E6 set of transactions. Tests are run for all 
report types and for all formats.
 
Typically there are five runs, and slowest and fastest are dropped off from results.
Then Average is calculated based on remaining three.

=== Results for Filesystem based storage 

These are based on multithread implementation and are run on Quad Core CPU.

 * 1E3
 ** link:./hw00/0.7.0-next-perf-fs-1E3-balance-txt.txt[1E3, Balance report, FS]
 ** link:./hw00/0.7.0-next-perf-fs-1E3-balance-group-txt.txt[1E3, Balance Group report, FS]
 ** link:./hw00/0.7.0-next-perf-fs-1E3-register-txt.txt[1E3, Register report, FS]
 * 1E6 
 ** link:./hw00/0.7.0-next-perf-fs-1E6-balance-txt.txt[1E6, Balance report, FS]
 ** link:./hw00/0.7.0-next-perf-fs-1E6-balance-group-txt.txt[1E6, Balance Group report, FS]
 ** link:./hw00/0.7.0-next-perf-fs-1E6-register-txt.txt[1E6, Register report, FS]

All results are here: link:./hw00/[hw00]

=== Results for Git based storage

These are based on currently single thread implementation:

 * link:./hw01/perf-git-1e3.txt[Git 1E3]
 * link:./hw01/perf-git-1e6.txt[Git 1E6]

