= Tackler

Tackler operates on stream of immutable transactions, and over this
transaction stream (or sub-selection of it) it generates different reports.

Stream is immutable, so it is possible to make multiple reports
over same data in one go. Currently all transactions are held in memory.

For parsing Tackler uses http://www.antlr.org/[ANTLR4].


== Consepts and names

Typically singular form of something is one instance, and plural is sequence.
For example Txn (single Transaction) or Txns (sequence of Transactions).

In case of tree-structures, child (singular) and childs (plural) is misspelled by purpose.

Tackler data model classes and objects are defined in link:../../core/src/main/scala/fi/sn127/tackler/model[core / model] package.


===== Date

All dates use subset of link:https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] format.

* ISO date `YYYY-MM-DD`
* ISO DateTime up to nanosecond resolutioin: `YYYY-MM-DDTHH:MM:SS.SSS`
* ISO DateTime with timezone offset or ZoneId

Internally all dates and time is handled as datetime with zone. If txn date does not have zone info,
then link:../tackler.conf[configured] default zone is used.

If timezone is offset (`+02:00`) then it is *not* adjusted by daylight saving times.
When on the other hand, timezone as ZoneId (`e.g. Europe/Helsinki`) is adjusted by daylight saving time.


===== Transaction (Txn, Txns)

Transaction is one isolated, self-containing accounting activity,
containing two or more postings to accounts which are involved with this activity.
Transaction also contains meta information (dates, codes, descriptions etc.) about this accounting action.

Sum of Transaction's postings must be zero.


===== Posting (post, posts)

Posting is activity on one account when account is either debited or credited.
Debit or credit of account is handled by positive or negative number in Tackler.

Posting also contains other information (comments, etc) on top of
account name and amount.

If this posting is last listed posting on current transaction
then amount could be left empty.

Posting with zero amount is not allowed.


===== Account (acc)

Account is single entry on structural hierarchy of accounts.

For example:

 Assets:Bank:Checking

In above `Assets` is root account, `Bank` is child of `Assets` and parent of `Checking`. 
If there are no other accounts under `Checking` in Chart of Accounts,
then `Checking` is leaf.


===== AccountTreeNode (AccTN, AccTNs)

One entry of Chart of Accounts, e.g. one entry in account tree,
where all used accounts are listed.

This contains information about tree structure: parent-name, depths,
own leaf-names, etc.

In default mode of operation, Tackler checks that all transactions postings
(e.g. accounts)  are listed on Chart of Accounts.  It is fatal error if there is
an account which is not listed. This can be lifted by link:../accounts.conf[configuration and command
line parameter].

=== Accumulator and Reporting

* AccountTreeNode, node in account tree (Chart of Accounts)
* BalanceTreeNode, node (row) in balance report, contains it's own balance and balance of childs
* RegisterPosting, posting which contains running total so far for this account


== Parser

For parsing Tackler uses http://www.antlr.org/[ANTLR4].

Parser definition is located 

 * link:../../core/src/main/antlr4/TxnLexer.g4[]
 * link:../../core/src/main/antlr4/TxnParser.g4[]

Input is fed to the Parser by link:../../core/src/main/scala/fi/sn127/tackler/parser/TacklerTxns.scala[core / parser / TacklerTxns]. 
Result of parsing (e.g. ANTLR  Parser Context) is converted to 
the link:../../core/src/main/scala/fi/sn127/tackler/model[Tackler Model] 
by link:../../core/src/main/scala/fi/sn127/tackler/parser/CtxHandler.scala[core / parser / CtxHandler]
helper class.

== Input

Input order of Txn can not be mandated. So there should be a stable way to sort transactions if
internal order (e.g. order of txns during one day and without time information)
is important.  In that case it is mandatory to provide  unique sorting information for each transaction.

Txn components are used in following order to find sort order
(in case of previous components have produced "same" sort order):

 timestamp, code, description, uuid

If fully deterministic and safe "distributed txn source"-proof sort
order is needed, then transactions must have UUIDs.
