= Tackler performance test setup

This directory contains tools and reference results for Tackler's performance testing.

Performance test data is generated by by link:../tools/generator[generator] tool.
Tools to run perf tests are located in link:./bin[bin].

See link:../docs/performance.adoc[Description of Performance] for explanation
of generated artificial test data.

With bigger data sets it is good idea to put this whole perf directory outside
of Tackler project directory.  If 1E5-1E6 data sets are inside project's directory,
your IDE might go nuts while it scans new files.


== Results

* link:./results/readme.adoc[Performance test result overview and hardware info]
* link:./results/perf-hw00.adoc[HW00 results]
* link:./results/perf-hw01.adoc[HW01 results]


== Test data

Test data is generated with link:../tools/generator[generator], version: 0.3.0


File count of test sets:
----
$ for ds in perf-1E?; do echo -n "$ds: "; find $ds -type f | wc -l; done
perf-1E3: 1000
perf-1E4: 10000
perf-1E5: 100000
perf-1E6: 1000000
----

Actual data size of test sets:
----
$ for ds in perf-1E?; do echo -n "$ds: "; (find $ds -type f | xargs cat ) | wc -c; done
perf-1E3: 86598
perf-1E4: 875945
perf-1E5: 8859367
perf-1E6: 89587889
----

Size on disk for test sets:
----
5.4M    perf-1E3
41M     perf-1E4
398M    perf-1E5
3.9G    perf-1E6
----


== Possible layout for perf test data

Content of `perf-test` directory, next to the `tackler`'s toplevel directory:

----
bin -> ../tackler/perf/bin/
data -> /path/to/volume/with/tackler/perf/data/
perf-coa.conf -> ../tackler/perf/perf-coa.conf
perf-fs.conf -> ../tackler/perf/perf-fs.conf
perf-git.conf -> ../tackler/perf/perf-git.conf
results -> ../tackler/perf/results/
----
