= TEP-XXXX: name

Single line description of enhancement

Longer paragraph with high level explanation of enhancement



== Journal file format

Journal file format changes, if any


== CLI changes

Changes to command line interface

* [ ] item


== CONF changes

Changes to conf-settings

* [ ] item


== Machinery

Changes to machinery

* [ ] item


=== API changes

Api changes to server or client interfaces.


==== Server API changes

Changes to server API

* [ ] item


==== Client API changes

Changes to client API or JSON model

* [ ] item


=== New dependencies

* [ ] link / url of new dependency
** [ ] Add and check licenses: link / url
** [ ] Is there NOTICE file(s)?
** [ ] Add license under link:../licenses[doc/licenses]
*** [ ] Add NOTICES under link:../licenses[doc/licenses]
** [ ] Add link of license to link:../readme.adoc[index]
** [ ] Add link to link:../../THANKS.adoc[THANKS]
** [ ] Add license material to binary distribution


== Reporting

Changes to reports or reporting


=== Balance report

Changes to balance report

* [ ] item


=== Balance Group report

Changes to balance group report

* [ ] item


=== Register report

Changes to register report

* [ ] item


== Exporting

Changes to exports or exporting

=== Equity export

Changes to equity export

* [ ] item


=== Identity export

Changes to identity export

* [ ] item


== Documentation

* [ ] link:../../README.adoc[]: is it a new noteworthy feature?
* [ ] link:../../CHANGELOG[]: add new item
* [ ] User docs
** [ ] user manual
*** [ ] cli-arguments
**** [ ] `--arg-1`
**** [ ] `--arg-2`
** [ ] tackler.conf
*** [ ] `setting-1`
*** [ ] `setting-2`
** [ ] accounts.conf
** [ ] examples
* [ ] Developer docs
** [ ] API changes
*** [ ] Server API changes
*** [ ] Client API changes


== Future plans

How and where to go from here?


== Tests

Normal, ok-case tests to validate functionality:

* [ ] test

=== Errors

Various error cases:

* [ ] e: error test

=== Perf

Is there need to run or create new perf tests?

* [ ] perf test

=== Metadata template for test coverage tracking

....
features:
  - feature:
      id: uuid
      subject: "todo: one-line description of main feature"

  - feature:
      id: uuid
      parent: uuid-of-parent
      subject: "todo: one-line description of sub feature"
      tests:
        errors:
          - error:
              id: uuid
              name: "todo: name of test class/method or test description file"
              desc: "todo: description"
        operations:
          - test:
              id: uuid
              name: "todo: name of test class/method or test description file"
              descriptions:
                - desc: "todo: description"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
		- ref: equity
....
