= Commodities

Commodities are something which have variable exchange rate.

Examples of commodities are: Helium, Oxygen, Gold, etc. Normally commodities need
an unit of measurement. This could be plain unit (e.g. `bar` for gases),
or you can specify that it is bars of Helium (`bar·He`).

Unit could be anything, as long as it is a valid single `ID` element. But for balance
and other reports will make more sense if you use specific unit for your commodity.

....
   Gas:Tank·102  298 bar·He
   Gas:Tank·208  195 bar·O2
....

It might be possible to do automatic unit conversions between commodities in future
(e.g. `42 oz:Au` -> `1306.3460256 g:Au` -> `1.3063460256 kg:Au`),
but at the moment that syntax is not valid commodity format.

== Transactions with mixed commodities

Transactions with mixed commodities without value positions are not allowed.

Example of mixed commodity transaction without value positions:

....
2017-05-01 this is not valid
 Vault:Bullion 1 g·Au
 Vault:Bullion 4 g·Ag
 Assets:Cash
....

Mixed commodities must be converted to common commodity with value positions:

....
2017-05-01 this is valid
 Vault:Bullion 1 g·Au @ 37.00 EUR
 Vault:Bullion 1 g·Ag @ 0.495 EUR
 Assets:Cash
....



== Example

Please see an accounting example for diving gas link:trimix-filling-station.adoc[Trimix Filling and Mixing Station].

It shows how to use different commodities and how to convert those commodities to momenetary values.

