= Commodities

Commodity is something which doesn't have value without unit of measurement.

Examples of commodities are Helium, Gold, Silver, etc. All of these need
an unit of measurement to make transaction record sensible
(for example `bar` for Helium or `oz` for Gold).

Typically it is possible to transform commodity transactions between same commodity,
but with different unit of measurement as long as there is well defined,
constant conversion between those units.

For example: `42 oz Au` -> `1306.3460256 g Au` -> `1.3063460256 kg Au`.

However, at the moment automatic commodity unit conversions are not supported with Tackler,
but this is something which will be implemented in the future.

Commodity name (and combined unit) has to be  a valid `ID` element (same rules applies as with account names).

For example, tracking Helium and Oxygen, you could use units `bar·He` and `bar·O2`:

....
   Gas:Tank·102  298 bar·He
   Gas:Tank·208  195 bar·O2
....

== Transactions with mixed commodities

Transactions with mixed commodities without value positions are not allowed.

Example of mixed commodity transaction without value positions:

....
2017-05-01 this is not valid
 Vault:Bullion 1 g·Au
 Vault:Bullion 4 g·Ag
 Assets:Cash
....

Mixed commodities must be converted to common commodity with value positions:

....
2017-05-01 this is valid
 Vault:Bullion 1 g·Au @ 37.00 EUR
 Vault:Bullion 1 g·Ag @ 0.495 EUR
 Assets:Cash
....



== Example

For example see an accounting example for scuba diving
link:trimix-filling-station.adoc[Trimix Filling and Mixing Station]. It demonstrates how to track different
commodities and how to convert those commodities to monetary values,