= Configuration Manual

Tackler configuration is controlled by conf-files and command line options.

There are provided configuration files for link:./tackler.conf[tackler.conf]
and example of link:./accounts.conf[accounts.conf] included in documentation folder.

These have examples and documentation for all available configuration variables.

You can override some of the configuration varibles with CLI options.

These configuration options which can be overridden by command line are documented
in link:./tackler.conf[tackler.conf] by 'CLI:' notation.


Tackler configuration file format is based HOCON syntax.
There is extensive documentation of HOCON and its capabilities available by
link:https://github.com/typesafehub/config/blob/master/HOCON.md[typesafe's HOCON project at github].


== Configuration finding and resolution rules

Active configuration is found following way:

* cmd-line args
* –cfg /path/to/cfg.conf
* find config by exe-path (ext conf-file)
* use internal default config

All config's are merged together (like a cake),
and the top-most defined value is what is used
by configuration.

From top to down this cake will be:

* cmd-line args
* external config file
* embedded default configuration

Together these will form active configuration, which is used.


== Relative paths with conf

Relative basedir-paths are always relative to the used cfg-file.

If it is external conf-file, then it is conf-file's directory.

If it is internal, embedded conf, then it is directory where executed jar is located.
