= Configuration

Tackler configuration is controlled by conf-files
and by command line options.

Example configuration files: link:./tackler.conf[] and  link:./accounts.conf[]
have example values and documentation for all configuration variables.

You can override some of the configuration varibles with CLI options.
These configuration options, and command line switches are documented
on link:./tackler.conf[].

Tackler configuration file format is HOCON, there is extensive 
documentation available on by
link:https://github.com/typesafehub/config/blob/master/HOCON.md[HOCON project at github].


== Configuration finding and resolution rules

Active configuration is found following way:

* cmd-line args
* –cfg /path/to/cfg.conf
* find config by exe-path (ext conf-file)
* use internal default config

All config's are merged together (like a cake),
and the top-most defined value is what is used
by configuration.

From top to down this cake will be:

* cmd-line args
* external config file
* embedded default configuration

Together these will form active configuration, which is used.


== Relative paths with conf

Relative basedir-paths are always relative to the used cfg-file.

If it is external conf-file, then it is conf-file's directory.

If it is internal, embeddeed conf, then it is directory where executed jar is located.
