= Git Storage

Using link:https://git-scm.com/[GIT] repository as storage system with Tackler.

Tackler has integrated support for git as storage system. Git support is provided
by link:http://www.eclipse.org/jgit/[JGit], which is pure java library implementing
the Git version control system.

Tackler supports use of multiple branches, and transactions sets can be referenced by standard git ways:

* by link:https://git-scm.com/docs/gitglossary#def_ref[ref names] (e.g. `refs/heads/master`, `refs/tags/Y2016`),
* by link:https://git-scm.com/docs/gitglossary#def_symref[symbolic refs] (`HEAD`, `master`, `Y2016`)
* directly by link:https://git-scm.com/docs/gitglossary#def_object_name[commit ids] (short `a7938d9b` or long form `a7938d9b61958d2cabea7503a7be89191d4fb31e` are supported).

Git storage is used as link:https://git-scm.com/docs/gitglossary#def_bare_repository[bare repository]. This has multiple advantages:

* Transaction data can be read directly from link:https://git-scm.com/docs/gitglossary#def_pack[pack files]
* Transaction data can be easily manipulated by server systems
* Transaction data is always in "clean state" from git perspective and it is extremely well defined with recorded commit ids

Git storage is also tested with set of one million (1E6) transactions.

== Why to use git as transaction data storage?

There are several advantages to use git as storage system for account data.
Git itself is very good link:https://git-scm.com/about[distributed version control system with many features].

Git has some very important features for Tackler and accounting in general:

* link:https://git-scm.com/about/info-assurance[Data assurance]
** Clean, possible audited, track record who has made or changed journal data
** Uniquely identified journal data which was used to generate reports (each report contains git metadata, e.g. commit id)

* link:https://git-scm.com/about/distributed[Data input collaboration, data distribution and backup]
** With all power of git it is very easy to distribute and share journal data input task
** Journal handling (data input) and reporting can be separated
** With good data shard merge conflicts can be kept at minimum

* link:https://git-scm.com/about/branching-and-merging[Topic based Accounting]
** With git's branches it is possible to create topic based accounting system where each branch is specific topic
** Topics could be used for auditing  or handling cleared and uncleared transactions
** These topics can be merged together in aggregate branches

== How to use git as storage

First you have to create transaction data on git. This is just normal journal data (transactions),
which are pushed to (bare) git repository.

For example:
....
git init --bare tackler-demo.git
git clone tackler-demo.git
cd tackler-demo
mkdir txns

cat > txns/txn-01.txn << EOF
2017-04-23 first demo transaction
 Expenses:Ice_cream  2
 Assets:Cash

EOF

git add txns/txn-01.txn
git commit -m 'first transaction'

cat > txns/txn-02.txn << EOF
2017-04-23 second demo transaction
 Expenses:Lemonade  1
 Assets:Cash

EOF

git add txns/txn-02.txn
git commit -m 'second transaction'

git push
....

Then you have to configure git storage, see link:tackler.conf[] for full explanation, but it could be as simple as:

....
basedir=.

input {
  storage = git
  git {
    repository = "tackler-demo.git"
    ref = "master"
    dir = "txns"
    suffix = ".txn"
  }
}

reporting {
  console = true
  reports = [ "balance", "register" ]
}

accounts.strict = false
....

If you named above config as `tackler-demo.conf`, then you could run default reports just by:

 java -jar tackler-cli.jar --cfg tackler-demo.conf

And it will produce something like that:

....
Txns size: 2
Git storage:
   commit:  cf9a1c3f6b0d34f4d28800062ad7d6e16189ccce
   ref:     master
   message: second transaction

BALANCE
-------
                 0.00   -3.00 Assets
                -3.00   -3.00 Assets:Cash
                 0.00    3.00 Expenses
                 2.00    2.00 Expenses:Ice_cream
                 1.00    1.00 Expenses:Lemonade
=====================
                 0.00

Git storage:
   commit:  cf9a1c3f6b0d34f4d28800062ad7d6e16189ccce
   ref:     master
   message: second transaction

REGISTER
--------
2017-04-23Z first demo transaction
            Assets:Cash                                   -2.00              -2.00
            Expenses:Ice_cream                             2.00               2.00
2017-04-23Z second demo transaction
            Assets:Cash                                   -1.00              -3.00
            Expenses:Lemonade                              1.00               1.00

Total processing time: 3019, parse: 641, reporting: 78
....

If you like to see your financial situatiation before you went crazy with lemonade, you could run
`git log` inside your journal's working copy, and figure out commit id for first transaction.

Let's say that it was `49551a0f3418486e576ce9076506fe94e2dbddf6`. You could also use short form of commit id:

  java -jar tackler-cli.jar --cfg tackler-demo.conf --input.git.commit 49551a0f

....
Txns size: 1
Git storage:
   commit:  49551a0f3418486e576ce9076506fe94e2dbddf6
   ref:     FIXED by commit
   message: first transaction

BALANCE
-------
                 0.00   -2.00 Assets
                -2.00   -2.00 Assets:Cash
                 0.00    2.00 Expenses
                 2.00    2.00 Expenses:Ice_cream
=====================
                 0.00

Git storage:
   commit:  49551a0f3418486e576ce9076506fe94e2dbddf6
   ref:     FIXED by commit
   message: first transaction

REGISTER
--------
2017-04-23Z first demo transaction
            Assets:Cash                                   -2.00              -2.00
            Expenses:Ice_cream                             2.00               2.00


Total processing time: 2879, parse: 600, reporting: 73
....

Notice that Tackler warns you (`FIXED by commit`)
that you are not anymore following ref and ref's head.

=== Difference between refs and commits

Tackler follows head of ref automatically, so ref is good way to follow
accounting branch as it evolves.

On the other hand, commit ids are fixed in time and they do not change.
Same way transaction data identified by commit id do not change over time.

So by specifying transaction data with commit id you create an immutable,
persistent uniquely identified view to the journal. Tackler records used
commit id on each report and it could be used to re-create same reports
or additional reports if there is ever need in future.

For long term referencing of some certain state it is also possible to create
a git link:https://git-scm.com/docs/gitglossary#def_tag[tag].

