= Installation

To use tackler you need

  * Java Runtime Environment (Java 8)
  * Tackler command line binary (`tackler-cli.jar`-file)


== Mimimal setup

The absolute minimum to run tackler is following setup:

----
./tackler-cli-x.y.z.jar
./txns/
./txns/journal.txn
----

With that setup run following command line:

 java -jar tackler-cli-x.y.z.jar --accounts.strict=false

This will produce balance and register reports without account name validation.

Default embedded configuration will try to find transaction data (files with `.txn` suffix)
on `txns`-directory next to the jar-file.


== Recommend layout

By default Tackler will try to find configuration file (`tackler.conf`) next to its jar-file.
You can also provide path to configuration file with `--cfg` option.

More sensible setup would be:

....
./bin/tackler-cli-x.y.z.jar
./bin/tackler.conf
./bin/accounts.conf
./txns/
./txns/YYYY/MM/journal-01.txn
./txns/YYYY/MM/journal-02.txn
...
....

Where `YYYY` and `MM` stand for time based data shard with year and month slides.

With this setup, configuration file link:./tackler.conf[tackler.conf] is located nex to the jar-file,
so configuration is auto-discovered.  Chart of Accounts (link:./accounts.conf[accounts.conf]) contains
accounts names and it is possible to do strict account name validation.

Minimal `tackler.conf` for above setup could be:

....
tackler {
  core {
    basedir = ../
    input {
      storage = fs
      fs {
        dir = "txns"
        glob = "**.txn"
      }
    }
    include "accounts.conf"
  }
}
....

With this setup, it is possible to run Tackler by:

 java -jar bin/tackler-cli-x.y.z.jar

and it will just work.


== Configuration

Please see link:./configuration.adoc[configuration] for information about how to tailor and configure system.

You can override some of the configuration varibles with CLI arguments.
These configuration variables, and command line switches are documented
in link:./tackler.conf[tackler.conf].


=== Chart of Accounts

By default it is fatal error if there is an unknown account within
transactions.  This can be turned off with:

`--accounts.strict=false`

but then there is no safety net against typos with account names.

With production systems, it is highly recommended to provide valid
Chart of Accounts and not to disable account name check.

Chart of accounts is defined either as part of main configuration or
as separate configuration file. See link:./accounts.conf[accounts.conf] for example configuration.
