= Installation

To use tackler you need

  * Java Runtime Environment (Java 8)
  * Tackler command line binary (jar-file)


== Mimimal setup

Default embedded configuration will try to find transaction data
(files with `.txn` suffix) on `txns`-directory next to the jar-file.

The absolute minimum to run tackler is following setup:

----
./tackler-cli-x.y.z.jar
./txns/
./txns/journal.txn
----

With that setup you can run:

 java -jar tackler-cli-x.y.z.jar --accounts.strict=false

And it will produce balance and register reports without account name validation.


== Recommend layout

By default Tackler will try to find configuration file (`tackler.conf`) next to its jar-file.
You can also provide path to configuration file with `--cfg` option.

More sensible setup could be for example:

....
./bin/tackler-cli-x.y.z.jar
./bin/tackler.conf
./bin/accounts.conf
./txns/
./txns/YYYY/MM/journal-01.txn
./txns/YYYY/MM/journal-02.txn
...
....

Where `YYYY` and `MM` stand for time based data shard with year and month slides.

Also with this setup, there is configuration file link:tackler.conf[tackler.conf]
and link:accounts.conf[accounts.conf] for Chart of Accounts. Configuration is
located next to the jar-file, so it is auto-discovered.

If above `tackler.conf` is something like:

....
basedir=../
input {
  storage = fs
  fs {
    dir = "txns"
    glob = "**.txn"
  }
}
include "accounts.conf"
....

then it is possible to run tackler by:

 java -jar bin/tackler-cli-x.y.z.jar

and it will just work.


== Configuration

Please see link:./configuration.adoc[configuration] for information about how to configure system.

You can override some of the configuration varibles with CLI arguments.
These configuration variables, and command line switches are documented
in link:./tackler.conf[tackler.conf].


=== Chart of Accounts

By default it is fatal error if there is an unknown account within
transactions.  This can be turned off with:

`--accounts.strict=false`,

but then there is no safety net against typos with account names.

With production systems, it is highly recommended to provide valid
Chart of Accounts and not to disable account name check.

Chart of accounts is defined either as part of main configuration or
as separate configuration file. See link:./accounts.conf[accounts.conf] for example configuration.
