= Installation Manual

This is installation manual for tackler command line.

To use tackler cli you will need

  * Java Runtime Environment (Java 8)
  * Tackler command line binary (`tackler-cli.jar`-file)


== Minimal setup

The absolute minimum to run tackler is following setup:

----
# Copy tacker-cli.jar to here
cp /path/to/downloaded/tackler-cli-x.y.z.jar tackler-cli.jar

# Create default folder for transaction data
mkdir txns

# Create some demo transactions
cat > txns/journal.txn << EOF
2017-06-01 first demo transaction
 Expenses:Ice_cream  2
 Assets:Cash

2018-06-02 second demo transaction
 Expenses:Lemonade  1
 Assets:Cash

EOF
----
The journal data file can not be empty (`txns/journal.txn` in above),
hence we create some demo data into it.

After above steps, content of demo folder should be:
----
./tackler-cli.jar
./txns/
./txns/journal.txn
----

Now you can run following command on that demo folder:

 java -jar ./tackler-cli.jar --accounts.strict=false

This will produce balance and register reports without account name validation.

Output should be something like below:

----
19:37:10.117 ERROR fi.sn127.tackler.core.Settings$ - Configuration file is not found or it is not readable: [/path/to/demo/tackler.conf]
19:37:10.119 WARN  fi.sn127.tackler.core.Settings$ - Settings will NOT use configuration file, only provided and embedded configuration will be used
19:37:10.181 INFO  fi.sn127.tackler.parser.TacklerTxns$ - Tackler Txns: FS: dir = /path/to/demo/txns
19:37:10.182 INFO  fi.sn127.tackler.parser.TacklerTxns$ - Tackler Txns: FS: glob = **.txn
Txns size: 2

BALANCE
-------
                 0.00   -3.00 Assets
                -3.00   -3.00 Assets:Cash
                 0.00    3.00 Expenses
                 2.00    2.00 Expenses:Ice_cream
                 1.00    1.00 Expenses:Lemonade
=====================
                 0.00


REGISTER
--------
2017-06-01Z first demo transaction
            Assets:Cash                                   -2.00              -2.00
            Expenses:Ice_cream                             2.00               2.00
2018-06-02Z second demo transaction
            Assets:Cash                                   -1.00              -3.00
            Expenses:Lemonade                              1.00               1.00


Total processing time: 1284, parse: 464, reporting: 80
----

Default embedded configuration will try to find transaction data (files with `.txn` suffix)
on `txns`-directory next to the jar-file.


== Recommend layout

By default Tackler will try to find configuration file (`tackler.conf`) next to its jar-file.
You can also provide path to configuration file with `--cfg` option.

More sensible setup would be:

....
./bin/tackler-cli.jar
./bin/tackler.conf
./bin/accounts.conf
./txns/
./txns/YYYY/MM/journal-01.txn
./txns/YYYY/MM/journal-02.txn
...
....

Where `YYYY` and `MM` stand for time based data shard with year and month slides.

With this setup, configuration file link:./tackler.conf[tackler.conf] is located nex to the jar-file,
so configuration is auto-discovered.  Chart of Accounts (link:./accounts.conf[accounts.conf]) contains
accounts names and it is possible to do strict account name validation.

Minimal `tackler.conf` for above setup could be:

....
tackler {
  core {
    basedir = ../
    input {
      storage = fs
      fs {
        dir = "txns"
        glob = "**.txn"
      }
    }
    include "accounts.conf"
  }
}
....

With this setup, it is possible to run Tackler by:

 java -jar ./bin/tackler-cli.jar

and it will just work.

There are more examples how to use tackler in link:./usage.adoc[Usage Guide].

== Configuration

Please see link:./configuration.adoc[Configuration Manual] for information about how to tailor and configure system.

You can override some of the configuration varibles with CLI arguments.
These configuration variables, and command line switches are documented
in link:./tackler.conf[tackler.conf].


=== Chart of Accounts

By default it is fatal error if there is an unknown account within
transactions.  This can be turned off with:

`--accounts.strict=false`

but then there is no safety net against typos with account names.

With production systems, it is highly recommended to provide valid
Chart of Accounts and not to disable account name check.

Chart of accounts is defined either as part of main configuration or
as separate configuration file. See link:./accounts.conf[accounts.conf] for example configuration.
