= Register report

Register report is report with running total of transactions

On left amount column, there is posting amount and on right running total for that account.
Register report is good way to find oddities and anomalies withing accounting data.

If internal order of register report (e.g. order of txns during one day and without time information)
is important, then it is mandatory to provide  unique sorting information for each transaction.
This means that each Txns must have  either `uuid` meta info field, or unique
combination of `time`, `code` and `description`  field values
(it is enough that combination or one field of above is unique).

Currently register report prints each transaction's time with date resolution,
but this will change in future (there will be an option to control register report's
time resolution).


----
REGISTER
--------
2017-01-01Z y 01
            a:b                                           20.00              20.00
            e:e0101                                      -20.00             -20.00
2017-01-01Z z 01
            a:b                                            1.00              21.00
            e:e0101                                       -1.00             -21.00
2017-01-01Z x 01
            a:b:c                                        300.00             300.00
            e:e0101                                     -300.00            -321.00
2017-01-02Z 02
            a:b                                            2.00              23.00
            e:e0102                                       -2.00              -2.00
2017-01-03Z (#001) 03
            a:b                                            2.10              25.10
            e:e0103                                       -2.10              -2.10
2017-01-03Z (#002) 03
            a:c                                            2.20               2.20
            e:e0103                                       -2.20              -4.30
2017-01-03Z (#003) 03
            a:b                                            2.30              27.40
            e:e0103                                       -2.30              -6.60
2017-01-03Z (#004) 03
            a:c                                            2.40               4.60
            e:e0103                                       -2.40              -9.00
----