= Balance Group report

Balance Group report is series of balance reports which are calculated
out of transactions grouped by selected criteria.

Available group operators (`reports.balance-group.group-by`) at the moment are:
`year`, `month`, `day`, `iso-week` and `iso-week-date`.

ISO-8601 rules are used for `iso-week` and `iso-week-date`.

For example balance group report could be made by weeks, when main report is done for month,
or it could be monthly when main balance report is year.

Other than that, the output is same as with balance report.

First (the leftmost) sum is sum of postings
which are directly debiting or crediting that account (account tree node).
If there are none such transactions,  then this first sum is zero.

Second sum is total balance sum for that account tree (root account and its children).


== Balance group report configuration

Balance Groups are selected by `reports.balance-group.group-by` conf-setting.

See link:tackler.conf[tackler.conf] and `reports.balance-group.*` for full
information of balance group report configuration options.

=== Account filtering

Accounts for Balance Group report can be filtered with global
`reporting.accounts` (conf+cli) or report specific `reports.balance-group.accounts`
setting (conf-only).

If there are no accounts matched with selected regexs with some balance group time period,
then that balance group is not is not printed / output at all.


== Example report

Below is part of link:../perf/refs/perf-1E3.ref.balgrp.txt[performance test output].
Transaction set is for one year, and each balance group is calculated
by weeks (iso-8601 weeks with UTC timezone 'Z').

----
BALANCE GROUPS
--------------
2016-W01Z
---------
                 0.00   -8.0000005 a
                 0.00   -8.0000005 a:ay2016
           -8.0000005   -8.0000005 a:ay2016:am01
                 0.00    8.0000005 e
                 0.00    8.0000005 e:ey2016
                 0.00    8.0000005 e:ey2016:em01
            2.0000002    2.0000002 e:ey2016:em01:ed01
            6.0000003    6.0000003 e:ey2016:em01:ed02
=====================
            0.0000000
2016-W02Z
---------
                 0.00   -114.0000019 a
                 0.00   -114.0000019 a:ay2016
         -114.0000019   -114.0000019 a:ay2016:am01
                 0.00    114.0000019 e
                 0.00    114.0000019 e:ey2016
                 0.00    114.0000019 e:ey2016:em01
            9.0000003      9.0000003 e:ey2016:em01:ed03
            8.0000002      8.0000002 e:ey2016:em01:ed04
           15.0000003     15.0000003 e:ey2016:em01:ed05
           18.0000003     18.0000003 e:ey2016:em01:ed06
           21.0000003     21.0000003 e:ey2016:em01:ed07
           16.0000002     16.0000002 e:ey2016:em01:ed08
           27.0000003     27.0000003 e:ey2016:em01:ed09
=====================
            0.0000000
...
----
