= Balance Group report

Balance Group report is group of balance reports calculated of transactions which
are grouped by selected criteria.

Available group by criteria at the moment is:
`year`, `month`, `day`, `iso-week` and `iso-week-date`.
See link:./tackler.conf[reports.balance-group.group-by] configuration option.

Typically balance group report could be by weeks, if main report is month,
or it could be monthly grouping is main report is over year.  Curre

Other than that, the output same as with balance report.

Below is part of link:../perf/refs/perf-1E3.ref.balgrp.txt[performance test output].
Main set of transactions is over one year, and each balance group is calculated
by weeks (iso-8601 weeks with UTC timezone).

----
BALANCE GROUPS
--------------
2016-W01Z
---------
                 0.00   -8.0000005 a
                 0.00   -8.0000005 a:ay2016
           -8.0000005   -8.0000005 a:ay2016:am01
                 0.00    8.0000005 e
                 0.00    8.0000005 e:ey2016
                 0.00    8.0000005 e:ey2016:em01
            2.0000002    2.0000002 e:ey2016:em01:ed01
            6.0000003    6.0000003 e:ey2016:em01:ed02
=====================
            0.0000000
2016-W02Z
---------
                 0.00   -114.0000019 a
                 0.00   -114.0000019 a:ay2016
         -114.0000019   -114.0000019 a:ay2016:am01
                 0.00    114.0000019 e
                 0.00    114.0000019 e:ey2016
                 0.00    114.0000019 e:ey2016:em01
            9.0000003      9.0000003 e:ey2016:em01:ed03
            8.0000002      8.0000002 e:ey2016:em01:ed04
           15.0000003     15.0000003 e:ey2016:em01:ed05
           18.0000003     18.0000003 e:ey2016:em01:ed06
           21.0000003     21.0000003 e:ey2016:em01:ed07
           16.0000002     16.0000002 e:ey2016:em01:ed08
           27.0000003     27.0000003 e:ey2016:em01:ed09
=====================
            0.0000000
...
----
