= Trimix Filling Station Accounting system

Trimix is breathing gas for diving which is mixture of Helium, Oxygen and Nitrogen.

This is an example how you could use Tackler for Trimix Filling station accounting purposes. 
This example is also part of Tacklers test setup and it is run with test target.

Trimix is made out of mix Helium and Nitrox or mix of Helium, Oxygen and compressed air. 
Helium is expensive and oxygen substantially cheaper (depending where do you live 
and how oxygen is available in your region).

At filling station you have to track individual users (how much and which gas they have used),
and how much do you have gas in your Helium and Oxygen tanks. Also you have to generate bills 
to users and reset Helium and Oxygen usage for each billed user.

Below are accounting entries for filling station, and an examples what kind of transactions
are recorded of one mixing of 18/45 (O2/He) trimix gas.

There is also an example how you could run and record and bill used gases.

==== Initial gas delivery

....
2017-01-01 (#123456789) Helium delivery (three tanks)
   Gas:He:Tank·102  298 bar·He
   Gas:He:Tank·103  298 bar·He
   Gas:He:Tank·104  298 bar·He
   Woikoski:He

2017-01-01 (#123456789) Oxygen delivery (one tank)
   Gas:O2:Tank·208  198 bar·O2
   Woikoski:O2
....


==== One 18/45 trimix blend with Helium (He) and Oxygen (O2)

....
2017-05-01 (mix-1234) tmx 18/45 D12L
   Gas:He:Tank·102  247 bar·He ; End pressure
   Gas:He:Tank·102 -273 bar·He ; Start pressure, negative pressure delta
   Mixer:jaa127:He

2017-05-01 (mix-1234) tmx 18/45 D12L
   ; this mix used 5 bar @ 50L tank
   Gas:O2:Tank·208  145 bar·O2 ; End pressure
   Gas:O2:Tank·208 -150 bar·O2 ; Start pressure, negative pressure delta
   Mixer:jaa127:O2
....

Why are there negative pressure deltas?

With initial starting pressures negative deltas makes more sense, 
so tank pressure degreses as gas is used. That way with negative deltas 
remaining pressure in storage tank (reported by gauge) match pressure
reported by accounting system.

Also with negative deltas, users accumulate posivite pressures, which in turn are 
zeroed with negative pressures within payment transactions.  So in overall, 
whole transaction flow makes more sense with real starting pressure 
and negative tank pressure deltas when mixing gas.


==== Accounting

Balance report by gas and by tanks

....
cli/run --cfg ../tests/commodity/gb.conf --reporting.accounts ^Gas:.*:Tank.*

Tank pressures
--------------

               272.00   272.00 bar·He Gas:He:Tank·102
               298.00   298.00 bar·He Gas:He:Tank·103
               298.00   298.00 bar·He Gas:He:Tank·104
               193.00   193.00 bar·O2 Gas:O2:Tank·208
============================
               868.00 bar·He
               193.00 bar·O2
....


===== Gas Balance per users.

....
cli/run --cfg ../tests/commodity/gb.conf --reporting.accounts ^User:.*:.*

Users Gas Balance
-----------------

                26.00   26.00 bar·He User:jaa127:He
                 5.00    5.00 bar·O2 User:jaa127:O2
============================
                26.00 bar·He
                 5.00 bar·O2
....

===== Generate billing transactions

....
2017-05-02  jaa127 outstanding payments
   ; Convert used gas (bars) to EUR
   User:jaa127:He -26 bar·He @ 1.25 EUR ; -32.50 EUR
   User:jaa127:O2  -5 bar·O2 @ 0.25 EUR ;  -1.25 EUR
   Billing:jaa127:Receivable  33.75 EUR
....


===== Generate billing reports

....
cli/run --cfg ../tests/commodity/gb-billing.conf

Outstanding payments
--------------------

                33.75   33.75 EUR Billing:jaa127:Receivable
                 0.00    0.00 bar·He User:jaa127:He
                 0.00    0.00 bar·O2 User:jaa127:O2
=========================
                33.75 EUR
                 0.00 bar·He
                 0.00 bar·O2
....


==== Trimix accounting and Tackler test setup

This example is also part of Tackler's test set, and it is run evertytime with test target.
Test data and setup is described below.

===== Test data

* Test steps
** link:../tests/commodity/ok/gas-blender-billing.exec[Billing]
** link:../tests/commodity/ok/gas-blender-mix-log.exec[Mixer log]
** link:../tests/commodity/ok/gas-blender-saldo.exec[Mixer Saldo]
** link:../tests/commodity/ok/gas-blender-tanks.exec[Storage tank pressures]
* link:../tests/commodity/ok/gas-blender[Accounting data]

===== Configuration

* link:../tests/commodity/gb.conf[General configuration for Gas Blending system]
* link:../tests/commodity/gb-accounts.conf[Chart of Accounts]
* link:../tests/commodity/gb-billing.conf[Configuration for billing reports]


===== Reports

Example reports

* link:../tests/commodity/ok/gas-blender-tanks.ref.bal.txt[Tank pressures]
* link:../tests/commodity/ok/gas-blender-saldo.ref.bal.txt[Used gas by divers]
* link:../tests/commodity/ok/gas-blender-mix-log.ref.reg.txt[Gas Blending entries (register)]
* link:../tests/commodity/ok/gas-blender-billing.ref.bal.txt[Billing statement]
