= Usage

To use tackler you have to have

  * Java Runtime Environment (Java 8)
  * Tackler binaries
  * Correct configuration for your setup

And last but not least you need some transaction data to play with.

If your installation follows recommended structure, 
then you can generate default reports immediately after 
you put some transaction data under `txns`-directory.

== Embedding Tackler

For embedding Tackler see:

* link:./server-api.adoc[Server API]
* link:./client-api.adoc[Client API]
* link:./json.adoc[Json Report output]

== CLI

After you have link:installation.adoc[installed Tackler], and you have some transaction data,
you can run tackler with command:

   java -jar tackler-cli-1.2.3.jar

Where `1.2.3` is version number of your installation.

To skip automatic configuration discovery mechanism, you can provide path 
to configuration file with `--cfg` argument.

   java tackler-cli-1.2.3.jar --cfg=/path/to/my/tackler.conf

See link:installation.adoc[installation guide] for minimal and recommended setup.


=== Input and output

* `--basedir`: provides base directory for all operations. All other relative paths are
relative to the basedir.


==== Input

There are two different ways to provide transaction data to Tackler.

Input can be either single file or  directory structure,
which contains accounting data in separate files.

===== Single input file

  --input.file path/to/txn-file

path can be absolute or relative path to the basedir.


===== Multiple `txn` -files and sharding

* `--input.fs.dir`: directory which holds `txn` -files (absolute or relative path to basedir).
* `--input.fs.glob`: glob to find `txn` -files under txn.dir

 e.g. *.txn for flat directories or **.txn for deep directory structures

One typical way to shard `txn` data is to use time based sharding, for example:

 * `year/month/day`
 * `year/iso-week/iso-week-date`


With data shard and glob-pattern it is very easy to generate reports with
only selected accounting data.  For example with shard based on iso-week-date
it is possible to generate weekly reports with following piece of bash:

....
report_year=$1
report_week=$2

java \
   -jar tackler-cli.jar \
   --basedir="$exe_dir/.." \
   --input.fs.dir="txns/$report_year/W$report_week" \
   --input.fs.glob="**.txn" \
   "$@"
....

If this feature is used (e.g. with shell or
link:https://github.com/typesafehub/config#optional-system-or-env-variable-overrides[environment arguments are used with conf])
then it is good idea to use as specialized `input.fs.dir` as possible. In that case scanned file set is as small as possible.
File scanning and glob matching starts from `input.fs.dir` and descents from there.

Tackler doesn't care how do you shard your data or if you don't shard it at all. 
It can easily handle huge single file txn collections: 100 000 (1E5) txns easily 
and one million (1E6) txns with some memory.  

However, with sharding memory requirements are smaller, 
there isn't basically any performance inpact with shard input, 
and sharding makes more sense with version control backend.

It's recommended to select some data shard scheme with production systems.

Regardless of used sharding scheme, it is possible to group txns with different
`group-by` operators.

===== Git storage

Please see link:git-storage.adoc[git storage] for full information about git based storage.

Addition to configuration, Git reference or commit id can be given from command line:

* `--input.git.ref` is for git reference (e.g. branch name), HEAD of that branch will be used
* `--input.git.commit` one single commit and tree defined by it will be used

These options are mutually exclusive with each other and with filesystem storage arguments (`input.fs.*`).


==== Reporting

Ordering of transaction is done by comparing `time`, `code`, `description` or `uuid`, 
in that order.  If `uuid` is not provided and ordering is not clear by other fields, 
then txn ordering is undefined for that txn.

If truly stable reporting output is needed (especially Register and Identity report),
then either Txns must have either `uuid` or unique `time`, `code` or `description`.


===== Selecting reports

Produced reports can be selected either by link:./tackler.conf[configuration] or CLI options:

 * `--reporting.reports "report1" "report2"`

Valid options are:
link:./report-balance.adoc[`balance`],
link:./report-balance-group.adoc[`balance-group`],
link:./report-register.adoc[`register`],

 * `--reporting.exports "export1" "export2"`

link:./export-equity.adoc[`equity`],
link:./export-identity.adoc[`identity`]


===== Selecting reports

Report formats can be selected either by link:./tackler.conf[configuration] or CLI options:

 * `--reporting.formats "frmt1" "frmt2"`

Valid options are: `txt` and `json`


===== Selecting accounts for reports

Accounts can be selected for reports either by setting global `reporting.accounts`
(conf-setting and command line) setting or with report specific selector.

Default selection for reports is "all accounts" and it can be selected with empty setting.

Command line example:

  --reporting.accounts "^Assets:.*" "^Expenses:.*"

All accounts:

  --reporting.accounts


Configuration example:

....
reporting {
  accounts = [ "^Assets:.*", "^Expenses:.*" ]
}
....

All accounts

....
reporting {
  accounts = [ ]
}
....

If There are no accounts matched for report then report's sub-section
is not printed / outputted at all (balance Group, register report).


===== Balance Group Report and GroupBy

link:./report-balance-group.adoc[Balance Group] report is
like link:./report-balance.adoc[Balance] report, but it will produce
several sub-reports for group of transactions. Typical examples are Balance report over month
and Balance Group report by weeks, or Balance report for week and Balance Group report based on iso-week-date or plain date.

Criteria could be: `year`, `month`, `date`, `iso-week`, `iso-week-date`

GroupBy is set by link:./tackler.conf[configuration (tackler.conf)].


==== Output

* `--reporting.console=true` will print reports on console

* `--output <basename>`: will print reports to separate files,
which are named based on basename.

Basename is path and name prefix for output reports, and it
can be either absolute path or relative path to basedir.

Actual file names will be:

For reports:

* `<output>.bal.txt`: link:./report-balance.adoc[Balance report]
* `<output>.balgrp.txt`: link:./report-balance-group.adoc[Balance Groups report]
* `<output>.reg.txt`: link:./report-register.adoc[Registry report]

For exports:

* `<output>.equity.txn`: Equity report
* `<output>.identity.txn`: Identity report

Exports are special reports, which are valid input for Tackler.
