= Usage

To use tackler you have to have

  * Java Runtime Environment (Java 8)
  * Tackler binaries
  * Correct configuration for your setup

And last but not least you need some transaction data to play with.

If your installation follows recommended structure, 
then you can generate default reports immediately after 
you put some transaction data under `txns`-directory.


== CLI

After you have installed Tackler, and you have some transaction data, 
you can run tackler with command:

   java -jar tackler-cli-1.2.3.jar

Where `1.2.3` is version number of your installation.

To skip automatic configuration discovery mechanism, you can provide path 
to configuration file with `--cfg` argument.

   java tackler-cli-1.2.3.jar --cfg=/path/to/my/tackler.conf



=== Input and output

* `--basedir`: provides base directory for all operations. All other relative paths are
relative to the basedir.


==== Input

There are two different ways to provide transaction data to Tackler.

Input can be either single file or  directory structure,
which contains accounting data in separate files.

===== Single input file

  --input.file path/to/txn-file

path can be absolute or relative path to the basedir.


===== Multiple `txn` -files and sharding

 * `--input.txn.dir`: directory which holds `txn` -files (absolute or relative path to basedir).
 * `--input.txn.glob`: glob to find `txn` -files under `txn.dir`
 ** e.g. `*.txn` for flat directories or `**.txn` for deep directory structures

One typical way to shard `txn` data is to use time based sharding, for example:

 * `year/month/day`
 * `year/iso-week/iso-week-date`


With sharding and glob-pattern it is very easy to generate reports with
only selected accounting data.  For example With iso-week-date sharding 
it is possible to generate weekly reports with following piece of bash:

....
report_year=$1
report_week=$2

java \
   -jar tackler-cli.jar \
   --basedir="$exe_dir/.." \
   --input.txn.dir="txns/$report_year/W$report_week" \
   --input.txn.glob="**.txn" \
   "$@"
....

If either shell or 
link:https://github.com/typesafehub/config#optional-system-or-env-variable-overrides[environment arguments are used with conf] 
then it is good to use those on `input.txn.dir` so that scanned file set is as small as possible.
File scanning and glob matching starts from `input.txn.dir` and descents from there.

Tackler doesn't care how do you shard your data or if you don't shard it at all. 
It can easily handle huge single file txn collections: 100 000 (1E5) txns easily 
and one million (1E6) txns with some memory.  

However, with sharding memory requirements are smaller, 
there isn't basically any performance inpact with shard input, 
and sharding makes more sense with version control backend.

So it's recommened to select some sharding scheme with production systems.

Regardless of used sharding scheme, it is possible to group txns with different
groupBy operators. 


==== Reporting

Ordering of transaction is done by comparing `time`, `code`, `description` or `uuid`, 
in that order.  If `uuid` is not provided and ordering is not clear by other fields, 
then txn ordering is undefined for that txn.

If truly stable reporting output is needed (especially Register and Identity report),
then either Txns must have either `uuid` or unique `time`, `code` or `description`.


===== Selecting reports

Produced reports can be selected either by configuration or CLI options:

 * `--reporting.reports "report1" "report2"`

Valid options are: `balance`, `balance-group`, `register`, `equity`, `identity`

===== Selecting accounts for reports

Accounts included with reports are selected with option:

 * `--reporting.accounts "^Assets:.*", "^Expenses:.*"`

All accounts are selected with empty selection.

If There are no accounts matched for report then report's sub-section
is not printed / outputted at all (balance Group, register report).

===== Balance Group Report and GroupBy

Balance Group report is like Balance report, but it will produce
several sub-reports for group of transactions. Typical examples are balance over month
and Balance Group report by weeks, or Balance report for week and Balance Group report based on iso-week-date or plain date.

Criteria could be: `year`, `month`, `date`, `iso-week`, `iso-week-date`

GroupBy is set by link:./tackler.conf[configuration (tackler.conf)].

==== Output

* `--reporting.console=true` will print reports on console

* `--output <basename>`: will print reports to separate files,
which are named based on basename.

Basename is path and name prefix for output reports, and it
can be either absolute path or relative path to basedir.

Actual file names will be:

For reports:

* `<output>.bal.txt`: Balance report
* `<output>.balgrp.txt`: Balance Groups report
* `<output>.reg.txt`: Registry report

For exports:

* `<output>.equity.txn`: Equity report
* `<output>.identity.txn`: Identity report

Exports are special reports, which are valid input for Tackler.
